### ISSUE TITLE
DynamicDataTypePackageFragmentInstaller compile error for IVersioned data types 

### ISSUE THREAD

**Issue by kasravi** [Orckestra/CMS-Foundation#239]
Older packages that has IVersioned data types and don't have VersionId field, face Compiler Error CS0535 during installation

Repro:
try to install package [Orckestra.Test.InstallingPageMeta.zip](https://github.com/Orckestra/CMS-Foundation/files/495432/Orckestra.Test.InstallingPageMeta.zip) on version 5.2

**Comment by burningice2866** [comment]
Looks like the same issue as https://github.com/Orckestra/CMS-Foundation/issues/227

**Comment by mawtex** [comment]
@burningice2866  Different issues - this issue (#239) relate to installing CMS Packages with dynamic data types generated on 5.1 or older versions (where new inherited interface on IPageMetaData introduce new column VersionId), while issue #227 relate to upgrading to 5.2 failing, if the site has page meta data already. The culprit is the extra interface in both situations though, but repros/fixes are distinct.
