### ISSUE TITLE
Multiple MVC functions on same C1 page triggers multiple post-actions and not just the intended post-action.

### ISSUE THREAD

**Issue by sgedda** [Orckestra/CMS-Foundation#331]
Are there any workaround regarding this, or should this be working? In my case i have a function declared in my TopMenu, `@Function("Account.LogOff") `which works just fine. Then I have a form added and when trying to post to its action `@using (Html.BeginForm("Form", "Profile", FormMethod.Post)` also Post-action for LogOff gets called which I obviously dont want.

Best Regards
Sebastian

**Comment by burningice2866** [comment]
@sgedda The issue is that all forms will post to the same page-url without any identifier of which Controller Action the form belongs to. 

You can either

 1. Add a hidden field inside your different forms with a identifier so you can later check on the server if your Post-action should handle the post or not. I personally like this approach and you can even generalize it so all your MVC Functions inherit from a base class that performs this logic ever time.

 2. Do ajax-post of the forms to explicit endpoints

**Comment by sgedda** [comment]
Thank you! Another hack/workaround would be something like this, set action for the form afterwards: 

```
    $().ready(function () {
        $("#my-form").attr("action", "/profile/form");
    });
```

**Comment by burningice2866** [comment]
@sgedda you can... the issue with that one is how to handle the return value if the Action does anything else than a redirect. 

Ie. if the Function/Action returns "Hello world", you would then have a blank page with nothing but the text "Hello world", since there is no C1 Page to handle the surrounding template of that function/action.
