### ISSUE TITLE
The label in Insert > Components should end with an ellipsis

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Foundation#349]
**Note**:

As we conventionally use a ellipsis ("...") for menu items that open popup windows (like Insert > Functions...), it makes sense to use it on the "Component" menu item, too: "Component...".

**Repro**:

1. Edit a page.
2. Click the Insert button.
3. Check the "Component" menu item.

**Expected**: It reads "Component..." (note the ellipsis it ends with).
**Actual**: It reads "Component" (no ellipsis)

![no-ellipsis-on-component-menu-item](https://cloud.githubusercontent.com/assets/14821915/22141596/64df111a-defb-11e6-9d5d-86dcc69a92ce.png)

**Comment by burningice2866** [comment]
Just on a more general note, then the ellipsis should be preceded with a space, since the ellipsis is not cutting of the word, but indicate that there could be more text after the word. 

And another note is that ellipsis has their own entity in html - http://line25.com/articles/10-html-entity-crimes-you-really-shouldnt-commit

> Did you know those three dots used to indicate a pause in a sentence are called an ‘ellipsis’? Rather than typing three periods or full stops it actually has it’s own glyph as the &hellip; HTML entity. The spacing between the dots in the entity is much tighter than the standard spacing between three full stops or periods.

**Comment by wwwysocki** [comment]
Verified on 20170124.2
